### ISSUE TITLE
Feedlines code for straight or curved

### ISSUE THREAD

**Issue by srpeiter** [feschmidt/pythonGDS#14]
Connected to Issue [`#9`](https://github.com/feschmidt/stcad/issues/9)

**Comment by feschmidt** [comment]
in progress in [`source_dev.rfcavities_hangers`](https://github.com/feschmidt/stcad/blob/testing/source_dev/rfcavities_hangers.py)

**Comment by srpeiter** [comment]
almost finished, going to finish this tommorow!

**Comment by srpeiter** [comment]
Finished the code for generating curved and straight feedlines. 
I made a separate class to generate the feedlines.
It is better to have a separate file for making the hangers.
I renamed the "rf_cavityhangers" to "rf_feedlines" and cleaned it up.
The code of the hanger I moved to the file "brokencode_hangers".
I guess to your test file "felix_test_RFhangers" is now broken.
Use my file: "sarwan_test_feedlines" to generate whatever feedline you want;).

**Comment by feschmidt** [comment]
@srpeiter could you please take a look at this: the curved option doesn't seem to work properly: When setting a radius to let's say 100 (more reasonable that 0.5), the curve gets pretty distorted...

Also a radius higher than 100 is not working?

So either there's an error in the artificial rounding, or we need to rewrite this in form of disks?

![001](https://user-images.githubusercontent.com/21104656/30594684-28ac1414-9d4f-11e7-928a-8757ced88485.png)

**Comment by mgely** [comment]
I just pushed code that solves this problem.
By the way, the examples of how to use my code are in the source_dev files
themselves. At the bottom is given some example code that will only run if
you run the file.
I use
if __name__ == '__main__':
## example code
