### ISSUE TITLE
Boolean operations

### ISSUE THREAD

**Issue by feschmidt** [feschmidt/pythonGDS#21]
@srpeiter 
Do the boolean operations work? See e.g. [utils.boolean](http://pythonhosted.org/gdsCAD/api/utils_api.html#gdsCAD.utils.boolean), seems to be **broken**. gdspy however seems to have such an option: [fast-boolean](http://gdspy.readthedocs.io/en/latest/geometry.html#fast-boolean)

Can we implement this by ourselves somehow? (Or just use gdspy for that matter?)

**Comment by srpeiter** [comment]
Hi Felix,

I did not use any boolean operations, so I do not actually know.
What do you want to use it for?
Implementing this can be somewhat time consuming.
I think it is better to use gdspy for this

**Comment by feschmidt** [comment]
Cannot seem to get it to work using gdspy. Workaround for now: Use LayoutBeamer...
