### ISSUE TITLE
CPW makes bend when it shouldn't

### ISSUE THREAD

**Issue by feschmidt** [feschmidt/pythonGDS#29]
@mgely 
When the list of cpw points has three subsequent elements with identical y-coordinates but different x-coordinates, CPW() makes a bend instead of a straight line, see image attached

The cpwlist that generates this issue:
`[[-2806.2000000000003, 3500], [-840.0000000000005, 3500], [-840.0000000000005, 1887.7888980384687], [-540.0000000000005, 1887.7888980384687], [-540.0000000000005, 3500], [-240.00000000000045, 3500], [-240.00000000000045, 1887.7888980384687], [59.999999999999545, 1887.7888980384687], [59.999999999999545, 3500], [359.99999999999955, 3500], [359.99999999999955, 1887.7888980384687], [659.9999999999995, 1887.7888980384687], [659.9999999999995, 3500], [959.9999999999995, 3500], [959.9999999999995, 1887.7888980384687], [1259.9999999999995, 1887.7888980384687], [1259.9999999999995, 3500], [1559.9999999999995, 3500], [1559.9999999999995, 1887.7888980384687], [1859.9999999999995, 1887.7888980384687], [1859.9999999999995, 3500], [2159.9999999999995, 3500], [3976.1999999999994, 3500]]`

![screenshot from 2018-03-04 15-39-30](https://user-images.githubusercontent.com/21104656/36946782-89aea39e-1fc2-11e8-98e9-70018fb90aa9.png)

**Comment by mgely** [comment]
Thats inevitable with the way the CPW class is coded at the moment. The
only way around this issue would be to have the class go through the list
of points to find any 3 aligned points and delete the one in the middle..
Mario

**Comment by feschmidt** [comment]
Fixed in [` 869aeb4`](https://github.com/feschmidt/stcad/commit/869aeb44c54d66ff8109107dc7efa9fa9d0ca3e3)
