### ISSUE TITLE
todo: Add TU Delft logo

### ISSUE THREAD

**Issue by feschmidt** [feschmidt/pythonGDS#5]
There is a dxf file but can we convert that to python code?

**Comment by feschmidt** [comment]
There seems to be an error with dxfimport:
`Traceback (most recent call last):`

  `File "felix_test.py", line 40, in <module>`
   
` chip.add_TUlogo()`
  
`File "/home/felix/Documents/github/stcad/source_dev/chip.py", line 114, in add_TUlogo`
   
` logo = cad.core.DxfImport('examples/TU_Delft_logo_Black.dxf',scale=1.0)`

`  File "/usr/local/lib/python2.7/dist-packages/gdsCAD-0.4.5-py2.7.egg/gdsCAD/core.py", line 2069, in DxfImport`

`    if isinstance(e, dxfgrabber.entities.LWPolyline):`

`AttributeError: 'module' object has no attribute 'entities'`

This issue was reported to `gdscad` a while back and should have been fixed, see [https://github.com/hohlraum/gdsCAD/issues/46](https://github.com/hohlraum/gdsCAD/issues/46)

**Comment by feschmidt** [comment]
@srpeiter

**Comment by srpeiter** [comment]
Yeah I have the same problem.
I read that this could be due to that the lines of this logo are not somehow a "single" polyline.
I do not understand this.
I am currently looking for a workaround.

**Comment by feschmidt** [comment]
Seems to "work" now after updating gdsCAD from git, but the logo is pretty distorted. Maybe connected to the single polyline issue. Still do not completely understand what is going on

**Comment by feschmidt** [comment]
low priority
